{
 "title": "WEB-APP",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(visited_locations,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "App state",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "app_enabled" }
   ]
  },
  {
   "title": "App status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "app_overloaded" }
   ]
  },
  {
   "title": "Total requests (per min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_requests{instance=\"[[Instance]]\"}[1m])",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Visited locations counter (by client)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "visited_locations{instance=~\"[[Instance]]\"}",
     "legendFormat": "Host: {{host}}"
    }
   ]
  }
 ]
}